spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tedu_store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
